### ISSUE TITLE
Failed to run fleet with an os error: no such file or directory

### ISSUE THREAD

**Issue by JmPotato** [dimensionhq/fleet#2]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1446531/164890326-eb916d9a-f9be-49f6-a31d-9b0630cb7751.png)

I try to run `fleet build --release` with my repo and it just prints out this error without any further information.

**To Reproduce**

1. Install fleet with `curl -L get.fleet.rs | sh` on macOS.
2. Clone https://github.com/tikv/tikv
3. `fleet build --release`

**Expected behavior**

The building should start normally.

**Screenshots**

As above.

**Desktop (please complete the following information):**

 - OS: macOS 12.3.1 (21E258)

**Comment by suptejas** [comment]
@VarunPotti and I are currently implementing a fix for a similar issue faced by another user, will keep you posted 😄

**Comment by VarunPotti** [comment]
Hey @JmPotato the bug has been fixed! Please run `cargo install fleet-rs --force` 😀.

**Comment by suptejas** [comment]
@JmPotato Let me know if this solved it for you, we'll close the issue then!

**Comment by IAMISSAM** [comment]
Hello, i have the same issue, and with installing via `cargo install fleet-rs --force` i still have the same issue

I'm on macOS 12.3.1, fleet version says 0.0.7, i was on nightly toolchain but i tried switch to stable, uninstall and reinstall fleet, but still

**Comment by VarunPotti** [comment]
Hey @IAMISSAM, can you share the fleet.toml file? And if `rd_enabled = true` please change that to false, the issue should be fixed.

**Comment by IAMISSAM** [comment]
Hello, here is my fleet.toml :
```toml
rd_enabled = true
fleet_id = "83504b5d-adbb-41a7-9a50-4815c347aaea"

[build]
sccache = "/Users/issam/.cargo/bin/sccache"
```

When i disable rd_enabled, i have the same issue

![image](https://user-images.githubusercontent.com/26183901/164976697-ffdf1057-f572-43b6-8656-a5190618b797.png)

**Comment by VarunPotti** [comment]
I see, is the target directory created?

**Comment by IAMISSAM** [comment]
No, i don't see any target directory inside my project

**Comment by VarunPotti** [comment]
What is the output `cargo run` gives? Does it throw a similar error?

**Comment by IAMISSAM** [comment]
`cargo run` works fine, and the program is running

**Comment by VarunPotti** [comment]
I see, will look into it, the `${PWD}/.cargo/config.toml` file is created right?

**Comment by IAMISSAM** [comment]
Inside the project directory, there is no `.cargo` directory

**Comment by VarunPotti** [comment]
That must be the issue will look into this.

**Comment by VarunPotti** [comment]
Hey @IAMISSAM, I tried building on MacOS 11 https://github.com/VarunPotti/fleet-actions/runs/6146796095?check_suite_focus=true, and it works! I seem to have fixed the error I will merge it into the master branch and publish this version into cargo, will notify you when done 😁

**Comment by VarunPotti** [comment]
Yep published now along with a github workflow to check if everything works! So you can run `cargo install fleet-rs --force` and you will be good to go!

**Comment by suptejas** [comment]
Let us know if this issue is resolved1

**Comment by IAMISSAM** [comment]
Yeah, can confirm this is working now, thanks

**Comment by JmPotato** [comment]
@VarunPotti @suptejas Hi, after upgrading the fleet-rs, there is something wrong with the `split-debuginfo` config field.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1446531/165016086-06d74261-ff8e-4b8a-b6cd-1df5a52aceb1.png">

**Comment by VarunPotti** [comment]
Hey @JmPotato, what version of cargo, rustc are you running? `split-debuginfo='...'` is specified in the [documentation](https://doc.rust-lang.org/cargo/reference/profiles.html) so it must work fine

**Comment by GrinderDeveloper** [comment]
This issue has seemed to be fixed. If this issue re-occurs, or you’d like to open another issue, please create one! If you feel like it needs to be reopened, reach out to me over at our Discord Server (https://discord.gg/RsTeV6rpqJ).

Grinder (Community Manager)

**Comment by messense** [comment]
> Hey @JmPotato, what version of cargo, rustc are you running? `split-debuginfo='...'` is specified in the [documentation](https://doc.rust-lang.org/cargo/reference/profiles.html) so it must work fine

I think you may have misunderstood that `split-debuginfo = '...'  # Platform-specific.` in the docs is a valid option. To me it looks like the author simply don't want to write out platform specific value for `split-debuginfo` in the docs not that `...` is a valid option.

See also https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo

cc https://github.com/napi-rs/napi-rs/discussions/1246
